---
output: slidy_presentation
---

# Challenge 1


Study the output of `str(surveys)`. How are the missing values being treated?


---

# Challenge 2


The function `nrow()` on a `data.frame` returns the number of rows. Use it,
in conjuction with `seq()` to create a new `data.frame` called
`surveys_by_10` that includes every 10th row of the survey data frame
starting at row 10 (10, 20, 30, ...)


---

# Challenge 3


The function `table()` tabulates observations.

```{r table, eval=FALSE}
expt <- c("treat1", "treat2", "treat1", "treat3", "treat1",
          "control", "treat1", "treat2", "treat3")
expt <- factor(expt)
table(expt)
```

* In which order are the treatments listed?
* How can you recreate this table with "`control`" listed last instead
of first?


---

# Challenge 4


Using pipes, subset the data to include individuals collected before 1995,
and retain the columns `year`, `sex`, and `weight.`


---

# Challenge 5


Create a new dataframe from the survey data that meets the following
criteria: contains only the `species_id` column and a column that contains
values that are the square-root of `hindfoot_length` values (e.g. a new column
`hindfoot_sqrt`). In this `hindfoot_sqrt` column, there are no NA values
and all values are < 3.

Hint: think about how the commands should be ordered


---

# Challenge 6


How many times was each `plot_type` surveyed?


---

# Challenge 7


Use `group_by()` and `summarize()` to find the mean, min, and max hindfoot
length for each species.


---

# Challenge 8


What was the heaviest animal measured in each year? Return the columns `year`,
`genus`, `species`, and `weight`.

Hint: Use `filter()` rather than `summarize()`.


---

# Challenge 9


Make a scatterplot of `hindfoot_length` vs `weight`, but only for the
`species_id`, `"DM"`.


---

# Challenge 10


Use dplyr to calculate the mean `weight` and `hindfoot_length` as well
as the sample size for each species.

Make a scatterplot of mean `hindfoot_length` vs mean `weight`, with
the sizes of the points corresponding to the sample size.


---

# Challenge 11


Make a plot of counts of `species_id` `"DM"` and `"DS"` by year.


---

# Challenge 12


Try using `geom_histogram()` to make a histogram visualization of the
distribution of `weight`.

Hint: You want `weight` as the x-axis aesthetic. Try specifying `bins`
in `geom_histogram()`.


---

# Challenge 13


A variant on the box plot is the violin plot. Use `geom_violin()` to
make violin plots of `hindfoot_length` by `species_id`.


---

# Challenge 14


- Calculate counts grouped by year, species_id, and sex

- make the faceted plot splitting further by sex (within each panel)

- color by sex rather than species


---

# Challenge 15


- Create a new R Markdown document.
- Delete all of the R code chunks and write a bit of Markdown (some sections, some italicized
text, and an itemized list).
- Convert the document to a webpage.


---

# Challenge 16


Add code chunks to

- Load the ggplot2 package
- Read the portal data
- Create a plot


---

# Challenge 17


Use chunk options to control the size of a figure and to hide the
code.


---

# Challenge 18


Try out a bit of in-line R code.



# Capstone project

Create and compile an R Markdown report:

1. Load the `combined.csv` data.

2. Create boxplots of weight by sex, _omitting individuals with
missing sex_.

3. Create a histogram of hindfoot lengths.

4. Create a scatterplot of hindfoot length vs weight for the species
`"DM"`, `"DO"`, and `"DS"`. _Use different colors for the three
species, and put the three species in different panels._

5. Create a table of counts of `"DM"` by plot type for the year 1977.

6. Create a line plot of the counts of `"DM"` in `"Rodent Exclosure"` plots over time.
